version: "3"

services:
  api:
    build: api/
    ports:
      - "1280:1233"
    depends_on:
      - db
      - db_manager
      - tesseract
    networks:
      my-network:
  db:
    image: bitnami/postgresql
    ports:
      - "1281:1234"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=image_processing
      - POSTGRESQL_PORT_NUMBER=1234
    networks:
      - my-network
  db_manager:
    build: db_manager/
    ports:
      - "1282:1235"
    depends_on:
      - db
    networks:
      my-network:
  tesseract:
    build: tesseract/
    ports:
      - "1283:1236"
    depends_on:
      - db
    networks:
      my-network:
  graph:
    build: graph/
    ports:
      - "1284:1237"
    depends_on:
      - tesseract
    networks:
      my-network:

networks:
  my-network:
